### ISSUE TITLE
哥们你自己创建了一个guix镜像？

### ISSUE THREAD

**Issue by tumashu** [pmeiyu/guix-config#1]

**Comment by tumashu** [comment]
从国内访问官方镜像慢的难以忍受啊。。。

**Comment by tumashu** [comment]
看到你的blog了，我也是从debian转过来的，也是一个emacser, 汗。。。。

**Comment by pmeiyu** [comment]
我自己的电脑上有Nginx caching mirror，另外我用Cloudflare为官方的服务器建了两个代理：

~- http://guix.mirror.pengmeiyu.com => https://ci.guix.info~
~- http://hydra.mirror.pengmeiyu.com => https://mirror.hydra.gnu.org~

更新:
- https://guix-mirror.pengmeiyu.com => https://berlin.guixsd.org
- https://hydra-mirror.pengmeiyu.com => https://mirror.hydra.gnu.org

如果访问官方服务器的速度非常慢，可以试试这两个Cloudflare代理。如果用Cloudflare代理的下载速度仍然非常慢，请及时反馈，我会协调建立国内的代理服务器。现在国内用Guix的人非常少，我知道的不到五个人，所以暂时没在意。

**Comment by tumashu** [comment]
我这边如果只使用官方的网址，速度只能达到10k/s，几乎无法使用，你架设的这个代理速度就会很多了
```
downloading from http://guix.mirror.pengmeiyu.com/nar/gzip/a3mdlq0919f9z541x661wd1wc69rwbhg-guix-locale-guix...
 guix-locale-guix  184KiB                                                                     95KiB/s 00:02 [##################] 100.0%

downloading from http://guix.mirror.pengmeiyu.com/nar/gzip/bfdrcq1zhgdrh8sz4ds38k0fliix9n8d-guile-git-0.2.0...
 guile-git-0.2.0  474KiB                                                                      79KiB/s 00:06 [##################] 100.0%

downloading from http://guix.mirror.pengmeiyu.com/nar/gzip/dv4l0g59lxffy5zlk5w4spy2s7lgl88q-guix-cli...
 guix-cli  1.1MiB                                                                            220KiB/s 00:05 [##################] 100.0%

downloading from http://guix.mirror.pengmeiyu.com/nar/gzip/rczg59vz1aw0fmvz23j5dfyigbnhb7ij-guix-locale-guix-packages...
 guix-locale-guix-packages  142KiB                                                            31KiB/s 00:05 [##################] 100.0%

downloading from http://guix.mirror.pengmeiyu.com/nar/gzip/pd0gqf0gcmzgpg0qmmcni9kfz3dyqxrg-guix-cli-modules...
 guix-cli-modules  267B                                                                       78KiB/s 00:00 [##################] 100.0%

downloading from http://guix.mirror.pengmeiyu.com/nar/gzip/6q71darrghxd6xy4bv4x2zj466r2hvzc-guix-system...
 guix-system  6.3MiB                                                                          59KiB/s 01:48 [##################] 100.0%

downloading from http://guix.mirror.pengmeiyu.com/nar/gzip/yp7pq3q3g8nff0clh4j28c9jb43zfvcd-guix-system-tests...
 guix-system-tests  296KiB                                                                    49KiB/s 00:06 [##################] 100.0%

downloading from http://guix.mirror.pengmeiyu.com/nar/gzip/s098gvvicfrbic3aaw32i01r26wwxr73-guix-system-modules...
 guix-system-modules  269B                                                                    12KiB/s 00:00 [##################] 100.0%

downloading from http://guix.mirror.pengmeiyu.com/nar/gzip/22nlknxa9pfmlchnncj84d3ysyw69q31-guix-system-tests-modules...
 guix-system-tests-modules  275B                                                              84KiB/s 00:00 [##################] 100.0%

downloading from http://guix.mirror.pengmeiyu.com/nar/gzip/cs0k8x787kk472vryyjp7a4fgxc963j1-guix-a27ed8fd3-modules...
 guix-a27ed8fd3-modules  26.7MiB                                                             548KiB/s 00:50 [##################] 100.0%

downloading from http://guix.mirror.pengmeiyu.com/nar/gzip/rwmvr6ir9rb25isy3dislndahh8ikvdz-guix-module-union...
 guix-module-union  2KiB                                                                     493KiB/s 00:00 [##################] 100.0%

downloading from http://guix.mirror.pengmeiyu.com/nar/gzip/414g2qhvgyngqar7q8k8vk09hnr3impr-guix-command...
 guix-command  565B                                                                          185KiB/s 00:00 [##################] 100.0%

downloading from http://guix.mirror.pengmeiyu.com/nar/gzip/ymgka1ylr9bmwbssv96i68j9rfgxjkvx-guix-daemon...
 guix-daemon  304B                                                                            95KiB/s 00:00 [##################] 100.0%
```

**Comment by tumashu** [comment]
我以前在 emacs 社区和大家介绍过 guix，后来有1－2个人也尝试安装过，不知道现在他们还用不用

**Comment by pmeiyu** [comment]
刚发现免费版Cloudflare不支持给多级子域名添加TLS证书，所以添加了两个新的一级子域名代理，以启用HTTPS：
- https://guix-mirror.pengmeiyu.com => https://berlin.guixsd.org
- https://hydra-mirror.pengmeiyu.com => https://mirror.hydra.gnu.org

**Comment by xaengceilbiths** [comment]
我会用emacs，也尝试过guix。可惜我现在用的一套桌面环境gnome-flashback-xmonad（以及魔改libwnck）很好用，却不好迁移，就暂时不用了。Google搜到你博客过来的，就回了个issue

**Comment by pmeiyu** [comment]
@xaengceilbiths 你太不清真了。为何不直接使用xmonad/bspwm/i3/sway等tiling window manager？我以前也曾觉得Gnome很方便，试图寻找在Gnome session里使用tiling window manager的方案，但是后来幡然醒悟，Gnome那一堆臃肿的软件都是浮云，i3(sway)＋Emacs＋Terminal就足够了，极简又高效。

**Comment by tumashu** [comment]
哈哈。。。。

**Comment by xaengceilbiths** [comment]
@meiyopeng 抛开容易折腾的tray（系统托盘）不说，想要在xmonad直接实现workspace-switcher（即libwnck套一个gnome-applet外壳）并不是一件容易的事。能在gnome-panel上时刻看到各个workspace有什么（及布局）是个很方便的功能。
当然什么都用emacs的另说。
![2019-05-08-225300_609x89_scrot](https://user-images.githubusercontent.com/31133127/57384981-204e5f00-71e4-11e9-9aa7-2dc697254aad.png)
)

**Comment by pmeiyu** [comment]
![image](https://user-images.githubusercontent.com/8529551/57440310-5b9b6d00-727a-11e9-9c38-ae2e7e116819.png)
我现在用的窗口管理器是sway，每个常用程序启动之后自动分配到一个固定的workspace，并且全屏。剩下的workspace用来放临时的程序。用 `Super+数字` 快捷键在各个workspace之间快速切换，比如 `Super+2` 切换到Emacs，`Super+3` 切换到浏览器。状态栏是waybar，可以非常方便地用script定制，不过内容是纯文本的，可以展示emoji和特殊的字体，但是没法展示图片。不过我觉得显示workspace缩略图并没有什么作用，还挤占本来就狭小的屏幕空间。

@xaengceilbiths
另外，你大概同时开了多个Emacs实例，这是不好的习惯。建议使用Emacs daemon＋emacsclient，或者用 `C-x 5 b` 和 `C-x 5 f` 创建多个frame。（养成良好的习惯，不要再用gedit啦）

**Comment by xaengceilbiths** [comment]
@meiyopeng Emacs daemon是应该试试。不过我很担心Emacs因为访问某个localhost:6666突然卡死的情况，当年用racket-mode就碰到过。

用gedit是因为几年前停止使用的windows的记事本的键绑定改不掉。但不得不承认gedit连C-f搜索都很慢

**Comment by cireu** [comment]
cloudflare代理还是有点不稳定，有时能上1m/s，有时就只有几十k

**Comment by pmeiyu** [comment]
现在用户太少，没动力搞国内镜像😂。欢迎加入新成立的Guix China讨论组商议解决方案。見：https://guix-china.github.io/blog/chat-rooms-for-guix-china/

**Comment by pmeiyu** [comment]
Guix中國鏡像已經上線。
https://guix-china.github.io/blog/guix-china-mirror-is-online-now/
